In [45]:
# Initial imports
import pandas as pd
import numpy as np

from path import Path
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [56]:
# Read data
games_df = pd.read_csv('Cleaned_Data/all_columns_df.csv')
games_df

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer_x,Critic_Score,User_Score,Year,Country,Total_Sales
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,2006.0,Japan,82.86
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,1985.0,Japan,40.24
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,2008.0,Japan,37.14
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,2017.0,NaN,36.60
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,2009.0,Japan,33.09
...,...,...,...,...,...,...,...,...,...,...,...,...
19857,19858,FirePower for Microsoft Combat Flight Simulator 3,Simulation,T,PC,GMX Media,Shockwave Productions,NaN,NaN,2004.0,NaN,0.01
19858,19859,Tom Clancy's Splinter Cell,Shooter,T,PC,Ubisoft,Ubisoft,NaN,NaN,2003.0,Europe,0.01
19859,19860,Ashita no Joe 2: The Anime Super Remix,Fighting,NaN,PS2,Capcom,Capcom,NaN,NaN,2002.0,Japan,0.01
19860,19861,Tokyo Yamanote Boys for V: Main Disc,Adventure,NaN,PSV,Rejet,Rejet,NaN,NaN,2017.0,NaN,0.01
19861,19862,NadePro!! Kisama no Seiyuu Yatte Miro!,Adventure,NaN,PS2,GungHo,GungHo Works,NaN,NaN,2009.0,NaN,0.01

In [57]:
games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19862 entries, 0 to 19861
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          19862 non-null  int64
 1   Name          19862 non-null  object
 2   Genre         19862 non-null  object
 3   ESRB_Rating   13925 non-null  object
 4   Platform      19862 non-null  object
 5   Publisher     19862 non-null  object
 6   Developer_x   19860 non-null  object
 7   Critic_Score  4706 non-null   float64
 8   User_Score    238 non-null    float64
 9   Year          19859 non-null  float64
 10  Country       11877 non-null  object
 11  Total_Sales   19862 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 1.8+ MB

In [58]:
a = games_df.groupby(['Platform'])['Critic_Score'].mean().to_dict()

In [59]:
games_df['Critic_Score1'] = games_df.Platform.map(a)

In [60]:
games_df

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer_x,Critic_Score,User_Score,Year,Country,Total_Sales,Critic_Score1
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,2006.0,Japan,82.86,6.781214
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,1985.0,Japan,40.24,8.133333
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,2008.0,Japan,37.14,6.781214
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,2017.0,NaN,36.60,7.848899
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,2009.0,Japan,33.09,6.781214
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19857,19858,FirePower for Microsoft Combat Flight Simulator 3,Simulation,T,PC,GMX Media,Shockwave Productions,NaN,NaN,2004.0,NaN,0.01,7.848899
19858,19859,Tom Clancy's Splinter Cell,Shooter,T,PC,Ubisoft,Ubisoft,NaN,NaN,2003.0,Europe,0.01,7.848899
19859,19860,Ashita no Joe 2: The Anime Super Remix,Fighting,NaN,PS2,Capcom,Capcom,NaN,NaN,2002.0,Japan,0.01,7.517500
19860,19861,Tokyo Yamanote Boys for V: Main Disc,Adventure,NaN,PSV,Rejet,Rejet,NaN,NaN,2017.0,NaN,0.01,7.342857
19861,19862,NadePro!! Kisama no Seiyuu Yatte Miro!,Adventure,NaN,PS2,GungHo,GungHo Works,NaN,NaN,2009.0,NaN,0.01,7.517500

In [62]:
games_df['Critic_Score2'] = np.where(games_df.Critic_Score.isna()==True, games_df.Critic_Score1, games_df.Critic_Score)

In [64]:
games_df.Critic_Score2

0         7.700000
1        10.000000
2         8.200000
3         7.848899
4         8.000000
           ...
19857     7.848899
19858     7.848899
19859     7.517500
19860     7.342857
19861     7.517500
Name: Critic_Score2, Length: 19862, dtype: float64

In [65]:
games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19862 entries, 0 to 19861
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           19862 non-null  int64
 1   Name           19862 non-null  object
 2   Genre          19862 non-null  object
 3   ESRB_Rating    13925 non-null  object
 4   Platform       19862 non-null  object
 5   Publisher      19862 non-null  object
 6   Developer_x    19860 non-null  object
 7   Critic_Score   4706 non-null   float64
 8   User_Score     238 non-null    float64
 9   Year           19859 non-null  float64
 10  Country        11877 non-null  object
 11  Total_Sales    19862 non-null  float64
 12  Critic_Score1  19686 non-null  float64
 13  Critic_Score2  19686 non-null  float64
dtypes: float64(6), int64(1), object(7)
memory usage: 2.1+ MB

In [66]:
a = games_df[['Critic_Score2', 'Total_Sales']]

In [67]:
a.corr()

               Critic_Score2  Total_Sales
Critic_Score2       1.000000     0.210145
Total_Sales         0.210145     1.000000

In [3]:
# Count no NaNs in each column
games_df.count()

Rank            19862
Name            19862
Genre           19862
ESRB_Rating     13925
Platform        19862
Publisher       19862
Developer_x     19860
Critic_Score     4706
User_Score        238
Year            19859
Country         11877
Total_Sales     19862
dtype: int64

In [4]:
# Drop columns
games_df.drop(['Rank', 'Name', 'User_Score', 'Year', 'Country'], axis=1, inplace=True)

In [5]:
games_df.count()

Genre           19862
ESRB_Rating     13925
Platform        19862
Publisher       19862
Developer_x     19860
Critic_Score     4706
Total_Sales     19862
dtype: int64

In [6]:
games_df.dropna().count()

Genre           4568
ESRB_Rating     4568
Platform        4568
Publisher       4568
Developer_x     4568
Critic_Score    4568
Total_Sales     4568
dtype: int64

In [7]:
games_df = games_df.dropna()
games_df.head(10)

,Genre,ESRB_Rating,Platform,Publisher,Developer_x,Critic_Score,Total_Sales
0,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,82.86
2,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,37.14
4,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,33.09
5,Role-Playing,E,GB,Nintendo,Game Freak,9.4,31.38
6,Platform,E,DS,Nintendo,Nintendo EAD,9.1,30.80
8,Platform,E,Wii,Nintendo,Nintendo EAD,8.6,30.22
11,Misc,E,Wii,Nintendo,Nintendo EAD,5.9,28.02
12,Party,E,X360,Microsoft Game Studios,Good Science Studio,6.7,24.00
13,Simulation,E,DS,Nintendo,Nintendo EAD,8.4,23.96
14,Racing,E,DS,Nintendo,Nintendo EAD,9.1,23.60

In [8]:
games_df.nunique()

Genre             20
ESRB_Rating        5
Platform          25
Publisher        216
Developer_x     1062
Critic_Score      86
Total_Sales      588
dtype: int64

In [9]:
games_df.Genre.value_counts()

Action              775
Role-Playing        608
Shooter             555
Sports              546
Platform            389
Racing              330
Adventure           258
Fighting            250
Misc                250
Strategy            192
Simulation          161
Puzzle              121
Action-Adventure     86
Music                21
Party                13
MMO                   9
Sandbox               1
Board Game            1
Education             1
Visual Novel          1
Name: Genre, dtype: int64

In [10]:
# Keep top 14 of Genre
top_Genre = games_df.Genre.value_counts().index[0:15]
games_df.Genre = np.where(games_df.Genre.isin(top_Genre), games_df.Genre, 'other')

/var/folders/gd/1878fbxd5zs899fs6znx1h_40000gn/T/ipykernel_58842/1481529943.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games_df.Genre = np.where(games_df.Genre.isin(top_Genre), games_df.Genre, 'other')

In [11]:
games_df.Genre.value_counts()

Action              775
Role-Playing        608
Shooter             555
Sports              546
Platform            389
Racing              330
Adventure           258
Misc                250
Fighting            250
Strategy            192
Simulation          161
Puzzle              121
Action-Adventure     86
Music                21
Party                13
other                13
Name: Genre, dtype: int64

In [12]:
games_df.Platform.value_counts()

X360    610
PS3     478
PC      404
PSP     400
PS2     358
Wii     340
GC      324
DS      312
GBA     297
PS      247
3DS     187
XB      110
NS      106
N64      97
PS4      93
WiiU     74
XOne     56
DC       29
GB       10
SNES     10
SAT       9
GBC       6
PSV       6
PSN       3
XBL       2
Name: Platform, dtype: int64

In [13]:
# Keep top 14 Platform
#top_Platform = games_df.Platform.value_counts().where(games_df.Platform.value_counts() > 100).index
top_Platform = games_df.Platform.value_counts().index[0:15]
games_df.Platform = np.where(games_df.Platform.isin(top_Platform), games_df.Platform, 'other')

/var/folders/gd/1878fbxd5zs899fs6znx1h_40000gn/T/ipykernel_58842/2898562611.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games_df.Platform = np.where(games_df.Platform.isin(top_Platform), games_df.Platform, 'other')

In [14]:
games_df.Platform.value_counts()

X360     610
PS3      478
PC       404
PSP      400
PS2      358
Wii      340
GC       324
DS       312
GBA      297
PS       247
other    205
3DS      187
XB       110
NS       106
N64       97
PS4       93
Name: Platform, dtype: int64

In [15]:
top_Publisher = games_df.Publisher.value_counts().index[0:15]
games_df.Publisher = np.where(games_df.Publisher.isin(top_Publisher), games_df.Publisher, 'other')
games_df.Publisher.value_counts()

/var/folders/gd/1878fbxd5zs899fs6znx1h_40000gn/T/ipykernel_58842/556782955.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games_df.Publisher = np.where(games_df.Publisher.isin(top_Publisher), games_df.Publisher, 'other')

other                          1648
Nintendo                        410
Electronic Arts                 327
Activision                      304
Ubisoft                         301
Sega                            213
Sony Computer Entertainment     209
THQ                             201
EA Sports                       195
Capcom                          166
Konami                          163
Square Enix                     110
Atlus                            96
Atari                            79
Namco Bandai                     75
2K Sports                        71
Name: Publisher, dtype: int64

In [16]:
games_df.Developer_x.value_counts()

Capcom                                  99
EA Canada                               97
EA Tiburon                              87
Ubisoft Montreal                        86
Konami                                  69
                                        ..
Bugbear Entertainment                    1
Cing Inc. / Town Factory                 1
Soleil Software Studio Inc.              1
Q Entertainment / Phantagram             1
Blue Byte Software / Related Designs     1
Name: Developer_x, Length: 1062, dtype: int64

In [17]:
top_Developer_x = games_df.Developer_x.value_counts().index[0:15]
games_df.Developer_x = np.where(games_df.Developer_x.isin(top_Developer_x), games_df.Developer_x, 'other')
games_df.Developer_x.value_counts()

/var/folders/gd/1878fbxd5zs899fs6znx1h_40000gn/T/ipykernel_58842/2239024486.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games_df.Developer_x = np.where(games_df.Developer_x.isin(top_Developer_x), games_df.Developer_x, 'other')

other                      3682
Capcom                       99
EA Canada                    97
EA Tiburon                   87
Ubisoft Montreal             86
Konami                       69
Nintendo EAD                 65
Traveller's Tales            58
Visual Concepts              51
Square Enix                  47
Ubisoft                      42
Sonic Team                   41
Vicarious Visions            40
Namco                        37
Omega Force                  35
Neversoft Entertainment      32
Name: Developer_x, dtype: int64

In [18]:
games_df.nunique()

Genre            16
ESRB_Rating       5
Platform         16
Publisher        16
Developer_x      16
Critic_Score     86
Total_Sales     588
dtype: int64

In [19]:
games_df

,Genre,ESRB_Rating,Platform,Publisher,Developer_x,Critic_Score,Total_Sales
0,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,82.86
2,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,37.14
4,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,33.09
5,Role-Playing,E,other,Nintendo,other,9.4,31.38
6,Platform,E,DS,Nintendo,Nintendo EAD,9.1,30.80
...,...,...,...,...,...,...,...
19790,Fighting,T,other,other,other,8.4,0.01
19792,Shooter,T,PC,Activision,other,7.0,0.01
19794,Action,E,GBA,Atlus,other,6.0,0.01
19800,Puzzle,E,GBA,other,other,6.7,0.01
19812,Simulation,T,PC,Ubisoft,other,7.0,0.01

In [20]:
games_df.dtypes

Genre            object
ESRB_Rating      object
Platform         object
Publisher        object
Developer_x      object
Critic_Score    float64
Total_Sales     float64
dtype: object

In [21]:
# Encoding object dtype columns
cat = games_df.select_dtypes(include='object')
cat = list(cat.columns)
cat

['Genre', 'ESRB_Rating', 'Platform', 'Publisher', 'Developer_x']

In [22]:
from sklearn.preprocessing import OneHotEncoder

# creating instance of one-hot-encoder
enc = OneHotEncoder(sparse=False)
# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(games_df[cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(cat)

encode_df

/opt/anaconda3/envs/mlenv/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Genre_Action,Genre_Action-Adventure,Genre_Adventure,Genre_Fighting,Genre_Misc,Genre_Music,Genre_Party,Genre_Platform,Genre_Puzzle,Genre_Racing,...,Developer_x_Nintendo EAD,Developer_x_Omega Force,Developer_x_Sonic Team,Developer_x_Square Enix,Developer_x_Traveller's Tales,Developer_x_Ubisoft,Developer_x_Ubisoft Montreal,Developer_x_Vicarious Visions,Developer_x_Visual Concepts,Developer_x_other
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4563,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4565,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [23]:
# Reset X dataframe index to merge with encode_df
games_df.reset_index(drop=True, inplace=True)
games_df

,Genre,ESRB_Rating,Platform,Publisher,Developer_x,Critic_Score,Total_Sales
0,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,82.86
1,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,37.14
2,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,33.09
3,Role-Playing,E,other,Nintendo,other,9.4,31.38
4,Platform,E,DS,Nintendo,Nintendo EAD,9.1,30.80
...,...,...,...,...,...,...,...
4563,Fighting,T,other,other,other,8.4,0.01
4564,Shooter,T,PC,Activision,other,7.0,0.01
4565,Action,E,GBA,Atlus,other,6.0,0.01
4566,Puzzle,E,GBA,other,other,6.7,0.01
4567,Simulation,T,PC,Ubisoft,other,7.0,0.01

In [24]:
# Merge one-hot encoded features and drop the originals
games_df = games_df.merge(encode_df, left_index=True, right_index=True)
games_df = games_df.drop(cat,1)
games_df

/var/folders/gd/1878fbxd5zs899fs6znx1h_40000gn/T/ipykernel_58842/2140457911.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  games_df = games_df.drop(cat,1)

,Critic_Score,Total_Sales,Genre_Action,Genre_Action-Adventure,Genre_Adventure,Genre_Fighting,Genre_Misc,Genre_Music,Genre_Party,Genre_Platform,...,Developer_x_Nintendo EAD,Developer_x_Omega Force,Developer_x_Sonic Team,Developer_x_Square Enix,Developer_x_Traveller's Tales,Developer_x_Ubisoft,Developer_x_Ubisoft Montreal,Developer_x_Vicarious Visions,Developer_x_Visual Concepts,Developer_x_other
0,7.7,82.86,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,8.2,37.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,8.0,33.09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9.4,31.38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,9.1,30.80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4563,8.4,0.01,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4564,7.0,0.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4565,6.0,0.01,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4566,6.7,0.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4567,7.0,0.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [35]:
X = games_df.drop('Total_Sales', axis = 1)
y = games_df['Total_Sales'].values

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [37]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [38]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=128, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [39]:
score = regressor.score(X_train, y_train)
print("R-squared:", score)

R-squared: 0.8994407755180568

In [40]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.9328237766340779
Mean Squared Error: 3.8065842132658303
Root Mean Squared Error: 1.9510469531166672

In [41]:
regressor.feature_importances_

array([3.14023132e-01, 7.53045603e-03, 6.97244775e-04, 8.50643224e-03,
       4.94484749e-03, 1.63387424e-02, 7.04158950e-04, 1.11076303e-02,
       1.93719952e-02, 1.14450979e-03, 1.66079964e-02, 3.05870821e-02,
       9.23011725e-03, 5.98199767e-03, 1.12471765e-01, 2.83700974e-03,
       2.08833713e-04, 1.88870760e-02, 7.99871013e-03, 1.22110340e-02,
       3.85677045e-06, 1.10555925e-02, 8.48682709e-03, 3.22914085e-02,
       3.84828973e-03, 1.50387144e-03, 6.27505568e-03, 5.10514680e-03,
       7.19216673e-03, 3.76708267e-03, 9.12831723e-03, 1.01167933e-02,
       1.28126792e-02, 1.90441208e-03, 1.85679120e-02, 1.11035929e-02,
       1.64010774e-03, 1.38496475e-02, 2.43596764e-04, 1.07860079e-02,
       1.98783020e-03, 3.03292431e-04, 6.89107388e-04, 2.74007141e-03,
       4.44532743e-03, 8.11772138e-04, 3.70949370e-04, 3.31803240e-02,
       1.06370356e-03, 8.48348069e-03, 1.34426228e-03, 8.10475053e-04,
       3.13971578e-03, 1.43795498e-02, 3.41906265e-04, 2.87605140e-03,
       8.32910236e-04, 3.42745509e-04, 9.09151222e-04, 2.18572077e-04,
       1.40547169e-01, 2.68891084e-05, 4.29407618e-04, 1.50558688e-03,
       1.76018901e-03, 1.53703562e-04, 1.18907708e-03, 6.25948704e-04,
       1.48183882e-04, 3.26951114e-03])

In [42]:
sorted(zip(regressor.feature_importances_, X.columns), reverse=True)

[(0.31402313193210263, 'Critic_Score'),
 (0.14054716903401568, 'Developer_x_Nintendo EAD'),
 (0.11247176511374261, 'Genre_Sports'),
 (0.033180324026703345, 'Publisher_Nintendo'),
 (0.032291408470845086, 'Platform_DS'),
 (0.03058708210660847, 'Genre_Role-Playing'),
 (0.01937199516555788, 'Genre_Platform'),
 (0.01888707595306961, 'ESRB_Rating_E'),
 (0.018567912014917073, 'Platform_Wii'),
 (0.016607996398841408, 'Genre_Racing'),
 (0.016338742418109065, 'Genre_Misc'),
 (0.014379549767021419, 'Publisher_other'),
 (0.01384964751048605, 'Platform_other'),
 (0.01281267917385315, 'Platform_PS4'),
 (0.012211034017240562, 'ESRB_Rating_M'),
 (0.01110763034554261, 'Genre_Party'),
 (0.011103592925081096, 'Platform_X360'),
 (0.011055592477368639, 'ESRB_Rating_T'),
 (0.010786007937304063, 'Publisher_Activision'),
 (0.010116793269958884, 'Platform_PS3'),
 (0.009230117245618109, 'Genre_Shooter'),
 (0.009128317228182886, 'Platform_PS2'),
 (0.008506432243792363, 'Genre_Adventure'),
 (0.008486827094563654, 'Platform_3DS'),
 (0.008483480691713835, 'Publisher_Sony Computer Entertainment'),
 (0.007998710133141624, 'ESRB_Rating_E10'),
 (0.00753045603349039, 'Genre_Action'),
 (0.00719216672950693, 'Platform_PC'),
 (0.006275055683190858, 'Platform_N64'),
 (0.005981997674822179, 'Genre_Simulation'),
 (0.005105146802329915, 'Platform_NS'),
 (0.004944847492615154, 'Genre_Fighting'),
 (0.004445327431968425, 'Publisher_Electronic Arts'),
 (0.0038482897272350096, 'Platform_GBA'),
 (0.003767082671398579, 'Platform_PS'),
 (0.003269511135500453, 'Developer_x_other'),
 (0.003139715777446541, 'Publisher_Ubisoft'),
 (0.0028760513957111836, 'Developer_x_EA Canada'),
 (0.002837009736790671, 'Genre_Strategy'),
 (0.0027400714095028576, 'Publisher_EA Sports'),
 (0.0019878301983389424, 'Publisher_Atari'),
 (0.0019044120847321253, 'Platform_PSP'),
 (0.0017601890091345077, "Developer_x_Traveller's Tales"),
 (0.0016401077391881846, 'Platform_XB'),
 (0.0015055868835851672, 'Developer_x_Square Enix'),
 (0.0015038714434691413, 'Platform_GC'),
 (0.0013442622811898357, 'Publisher_Square Enix'),
 (0.00118907708132732, 'Developer_x_Ubisoft Montreal'),
 (0.001144509788549305, 'Genre_Puzzle'),
 (0.0010637035586615678, 'Publisher_Sega'),
 (0.0009091512219184017, 'Developer_x_Namco'),
 (0.0008329102357266096, 'Developer_x_EA Tiburon'),
 (0.0008117721384614864, 'Publisher_Konami'),
 (0.0008104750526202998, 'Publisher_THQ'),
 (0.000704158950325402, 'Genre_Music'),
 (0.0006972447750099158, 'Genre_Action-Adventure'),
 (0.0006891073884796057, 'Publisher_Capcom'),
 (0.0006259487037648262, 'Developer_x_Vicarious Visions'),
 (0.00042940761756874335, 'Developer_x_Sonic Team'),
 (0.0003709493698753167, 'Publisher_Namco Bandai'),
 (0.0003427455085472149, 'Developer_x_Konami'),
 (0.00034190626458218174, 'Developer_x_Capcom'),
 (0.0003032924313391591, 'Publisher_Atlus'),
 (0.0002435967637199643, 'Publisher_2K Sports'),
 (0.0002185720772045747, 'Developer_x_Neversoft Entertainment'),
 (0.00020883371300881872, 'Genre_other'),
 (0.00015370356165598836, 'Developer_x_Ubisoft'),
 (0.00014818388228415654, 'Developer_x_Visual Concepts'),
 (2.6889108388949955e-05, 'Developer_x_Omega Force'),
 (3.856770451370964e-06, 'ESRB_Rating_RP')]